// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.3
// source: kadev-rk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeySignal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Keydown bool   `protobuf:"varint,2,opt,name=keydown,proto3" json:"keydown,omitempty"`
	Os      string `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
}

func (x *KeySignal) Reset() {
	*x = KeySignal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kadev_rk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeySignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySignal) ProtoMessage() {}

func (x *KeySignal) ProtoReflect() protoreflect.Message {
	mi := &file_kadev_rk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySignal.ProtoReflect.Descriptor instead.
func (*KeySignal) Descriptor() ([]byte, []int) {
	return file_kadev_rk_proto_rawDescGZIP(), []int{0}
}

func (x *KeySignal) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KeySignal) GetKeydown() bool {
	if x != nil {
		return x.Keydown
	}
	return false
}

func (x *KeySignal) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

var File_kadev_rk_proto protoreflect.FileDescriptor

var file_kadev_rk_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x61, 0x64, 0x65, 0x76, 0x2d, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x72, 0x6b, 0x22, 0x49, 0x0a, 0x09, 0x4b, 0x65, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x64, 0x6f, 0x77, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x64, 0x6f, 0x77, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kadev_rk_proto_rawDescOnce sync.Once
	file_kadev_rk_proto_rawDescData = file_kadev_rk_proto_rawDesc
)

func file_kadev_rk_proto_rawDescGZIP() []byte {
	file_kadev_rk_proto_rawDescOnce.Do(func() {
		file_kadev_rk_proto_rawDescData = protoimpl.X.CompressGZIP(file_kadev_rk_proto_rawDescData)
	})
	return file_kadev_rk_proto_rawDescData
}

var file_kadev_rk_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kadev_rk_proto_goTypes = []any{
	(*KeySignal)(nil), // 0: rk.KeySignal
}
var file_kadev_rk_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kadev_rk_proto_init() }
func file_kadev_rk_proto_init() {
	if File_kadev_rk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kadev_rk_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KeySignal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kadev_rk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kadev_rk_proto_goTypes,
		DependencyIndexes: file_kadev_rk_proto_depIdxs,
		MessageInfos:      file_kadev_rk_proto_msgTypes,
	}.Build()
	File_kadev_rk_proto = out.File
	file_kadev_rk_proto_rawDesc = nil
	file_kadev_rk_proto_goTypes = nil
	file_kadev_rk_proto_depIdxs = nil
}
